/**
 * Auth store — persists the Supabase session + any pending login state to a JSON file
 * under Electron's userData directory.
 *
 * The session contains the user's access_token and refresh_token. Both are sensitive:
 *   - access_token is a short-lived (~1h) JWT the api accepts as a bearer credential.
 *   - refresh_token is long-lived; whoever has it can mint access_tokens until the user
 *     explicitly signs out or Supabase revokes it.
 *
 * For v1 we store them in a plain JSON file with restrictive file permissions (0o600
 * on POSIX; Windows relies on the user's profile ACLs). This matches what Linear /
 * Cursor / GitHub CLI do for their desktop sessions. A later pass can upgrade to the
 * OS keychain via `keytar` once we add a native-module build step.
 *
 * This module is intentionally decoupled from `electron` — the Electron adapter lives
 * alongside it and supplies the userData path. Keeps this testable in vitest.
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';

export interface DesktopSession {
  /** Supabase user id (uuid). Stored so the UI can show "signed in as …". */
  readonly userId: string;
  /** Supabase access token (JWT). Expires around expiresAt. */
  readonly accessToken: string;
  /** Supabase refresh token. Long-lived. */
  readonly refreshToken: string;
  /** Unix seconds when the access token expires. */
  readonly expiresAt: number;
  /** Optional email for display. */
  readonly email?: string;
}

export interface AuthStateFile {
  /** Current signed-in session, if any. */
  session?: DesktopSession;
  /** State/nonce generated by beginLogin. Cleared on successful callback or timeout. */
  pendingState?: {
    readonly nonce: string;
    /** Unix ms. Callbacks older than this are rejected. */
    readonly expiresAt: number;
  };
}

const EMPTY: AuthStateFile = {};

export interface AuthStoreOptions {
  /** Absolute path to the userData directory (typically from Electron's app.getPath). */
  readonly userDataDir: string;
  /** Filename inside userDataDir. Defaults to 'auth.json'. */
  readonly filename?: string;
}

export class AuthStore {
  private readonly filePath: string;
  private cache: AuthStateFile = EMPTY;
  private loaded = false;

  constructor(opts: AuthStoreOptions) {
    this.filePath = path.join(opts.userDataDir, opts.filename ?? 'auth.json');
  }

  /** Read the file from disk; if absent or corrupt, start fresh. */
  async load(): Promise<void> {
    try {
      const raw = await fs.readFile(this.filePath, 'utf8');
      const parsed = JSON.parse(raw) as unknown;
      if (isAuthStateFile(parsed)) {
        this.cache = parsed;
      } else {
        this.cache = EMPTY;
      }
    } catch (err) {
      // ENOENT on first run is normal. Any other error (permissions, corruption) → empty.
      const code = (err as NodeJS.ErrnoException | undefined)?.code;
      if (code !== 'ENOENT') {
        console.warn('[auth-store] load failed, starting fresh:', err);
      }
      this.cache = EMPTY;
    }
    this.loaded = true;
  }

  getSession(): DesktopSession | undefined {
    this.assertLoaded();
    return this.cache.session;
  }

  getPendingState(): AuthStateFile['pendingState'] {
    this.assertLoaded();
    const p = this.cache.pendingState;
    // Expire lazily on read — no background sweeper needed.
    if (p && p.expiresAt < Date.now()) return undefined;
    return p;
  }

  async setPendingState(nonce: string, ttlMs: number): Promise<void> {
    this.assertLoaded();
    this.cache = {
      ...this.cache,
      pendingState: { nonce, expiresAt: Date.now() + ttlMs },
    };
    await this.flush();
  }

  async clearPendingState(): Promise<void> {
    this.assertLoaded();
    if (!this.cache.pendingState) return;
    const { pendingState: _discard, ...rest } = this.cache;
    this.cache = rest;
    await this.flush();
  }

  async setSession(session: DesktopSession): Promise<void> {
    this.assertLoaded();
    // Clear pendingState as part of accepting a session — a fresh sign-in supersedes.
    const { pendingState: _discard, ...rest } = this.cache;
    this.cache = { ...rest, session };
    await this.flush();
  }

  async clearSession(): Promise<void> {
    this.assertLoaded();
    if (!this.cache.session) return;
    const { session: _discard, ...rest } = this.cache;
    this.cache = rest;
    await this.flush();
  }

  private assertLoaded(): void {
    if (!this.loaded) {
      throw new Error('AuthStore.load() must be called before reading/writing');
    }
  }

  private async flush(): Promise<void> {
    const dir = path.dirname(this.filePath);
    await fs.mkdir(dir, { recursive: true });
    const json = JSON.stringify(this.cache, null, 2);
    // Write atomically: write tmp file, then rename. Prevents a half-written file on
    // power loss / app crash.
    const tmp = `${this.filePath}.tmp`;
    await fs.writeFile(tmp, json, { encoding: 'utf8', mode: 0o600 });
    await fs.rename(tmp, this.filePath);
  }
}

function isAuthStateFile(v: unknown): v is AuthStateFile {
  if (typeof v !== 'object' || v === null) return false;
  const o = v as Record<string, unknown>;
  if (o['session'] !== undefined && !isSession(o['session'])) return false;
  if (o['pendingState'] !== undefined && !isPendingState(o['pendingState'])) return false;
  return true;
}

function isSession(v: unknown): v is DesktopSession {
  if (typeof v !== 'object' || v === null) return false;
  const o = v as Record<string, unknown>;
  return (
    typeof o['userId'] === 'string' &&
    typeof o['accessToken'] === 'string' &&
    typeof o['refreshToken'] === 'string' &&
    typeof o['expiresAt'] === 'number' &&
    (o['email'] === undefined || typeof o['email'] === 'string')
  );
}

function isPendingState(v: unknown): v is NonNullable<AuthStateFile['pendingState']> {
  if (typeof v !== 'object' || v === null) return false;
  const o = v as Record<string, unknown>;
  return typeof o['nonce'] === 'string' && typeof o['expiresAt'] === 'number';
}
